# Generated by Django 5.0.2 on 2024-07-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug_remove_product_images_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
